# Generated by Django 5.2.5 on 2025-09-17 00:21

from django.db import migrations, models

def transfer_categories_forward(apps, schema_editor):
    Product = apps.get_model('products', 'Product')

    for product in Product.objects.iterator():
        if product.category_id:
            product.categories.add(product.category)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='products.productcategory', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='fact',
            field=models.TextField(blank=True, null=True, verbose_name='Интересный факт о продукте'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon_photo',
            field=models.ImageField(blank=True, help_text='Маленькое фото для инлайн-режима.', null=True, upload_to='product_icons/', verbose_name='Фото-иконка (для поиска)'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(blank=True, help_text='Фото, которое отправляется после добавления продукта.', null=True, upload_to='product_main_photos/', verbose_name='Основное фото'),
        ),
        migrations.RunPython(
            code=transfer_categories_forward,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
