# Generated by Django 5.2.5 on 2025-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Полный текст о челлендже.', verbose_name="Текст 'О проекте'")),
                ('media_file', models.FileField(blank=True, null=True, upload_to='about_media/', verbose_name='Медиафайл')),
                ('media_type', models.CharField(blank=True, choices=[('PHOTO', 'Фото'), ('VIDEO', 'Видео'), ('DOCUMENT', 'Документ'), ('AUDIO', 'Аудио')], max_length=10, null=True, verbose_name='Тип медиафайла')),
            ],
            options={
                'verbose_name': 'О проекте',
                'verbose_name_plural': 'О проекте',
            },
        ),
        migrations.CreateModel(
            name='BotTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(default="Добро пожаловать в челлендж '400 продуктов'! Я помогу вам отслеживать ваш прогресс.", help_text='Отображается после успешной авторизации.', verbose_name='Приветственное сообщение')),
                ('request_contact_message', models.TextField(default='Здравствуйте! Для участия в челлендже, пожалуйста, поделитесь своим контактом.', help_text='Первое сообщение пользователю при команде /start, если он не авторизован.', verbose_name='Запрос номера телефона')),
                ('request_fio_message', models.TextField(default='Отлично! Теперь, пожалуйста, введите ваше ФИО.', help_text='Сообщение с запросом ФИО пользователя.', verbose_name='Запрос ФИО')),
                ('request_hw_message', models.TextField(default='Спасибо! И последний шаг: введите ваш рост (в см) и вес (в кг) через пробел.\n\nНапример: 180 75', help_text='Сообщение с запросом роста и веса.', verbose_name='Запрос роста и веса')),
                ('registration_success_message', models.TextField(default='Регистрация успешно завершена! Ваш челлендж начался.', help_text='Отображается после ввода всех данных.', verbose_name='Сообщение об успешной регистрации')),
                ('already_authorized_message', models.TextField(default='Вы уже авторизованы.', help_text='Когда пользователь с контактом пытается снова отправить контакт.', verbose_name='Сообщение для уже авторизованных')),
                ('main_menu_message', models.TextField(default='Вы в главном меню.', help_text='Текст, который видит пользователь в главном меню.', verbose_name='Сообщение главного меню')),
                ('menu_return_message', models.TextField(default='Вы вернулись в главное меню.', help_text="Отображается при нажатии на кнопку 'Вернуться в меню'.", verbose_name='Сообщение о возврате в меню')),
                ('faq_list_title', models.TextField(default='Часто задаваемые вопросы:', help_text='Текст, который отображается над списком вопросов в разделе FAQ.', verbose_name='Заголовок списка FAQ')),
                ('suggest_product_prompt', models.TextField(default='Если вы не увидели определенный продукт в нашем списке, то можете написать его сюда, мы рассмотрим и добавим его в ближайшее время.', help_text="Отображается при нажатии на кнопку 'Предложить продукт'.", verbose_name='Запрос на предложение продукта')),
                ('suggest_product_success', models.TextField(default='Спасибо! Ваше предложение отправлено на рассмотрение.', help_text='Отображается после того, как был предложен продукт.', verbose_name='Успешное предложение продукта')),
            ],
            options={
                'verbose_name': 'Тексты бота',
                'verbose_name_plural': 'Тексты бота',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Краткий текст вопроса.', max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(help_text='Полный текст ответа.', verbose_name='Ответ')),
                ('media_file', models.FileField(blank=True, help_text='Опциональный файл для отправки (фото, видео, документ, аудио).', null=True, upload_to='faq_media/', verbose_name='Медиафайл')),
                ('media_type', models.CharField(blank=True, choices=[('PHOTO', 'Фото'), ('VIDEO', 'Видео'), ('DOCUMENT', 'Документ'), ('AUDIO', 'Аудио')], help_text='Необходимо указать тип, если вы прикрепили медиафайл.', max_length=10, null=True, verbose_name='Тип медиафайла')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке будет вопрос.', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_link', models.URLField(default='https://t.me/your_community_link', help_text='URL-адрес на группу единомышленников.', verbose_name='Ссылка на группу единомышленников')),
            ],
            options={
                'verbose_name': 'Группа единомашленников',
                'verbose_name_plural': 'Группа единомашленников',
            },
        ),
    ]
