# Generated by Django 5.2.5 on 2025-09-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottexts',
            name='welcome_message',
            field=models.TextField(default='Добро пожаловать в челлендж «400 продуктов»! Я помогу вам отслеживать ваш прогресс.', help_text='Отображается после успешной авторизации.', verbose_name='Приветственное сообщение'),
        ),
    ]
