# Generated by Django 5.2.5 on 2025-09-17 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_bottexts_welcome_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproject',
            name='media_type',
            field=models.CharField(blank=True, choices=[('PHOTO', 'Фото'), ('VIDEO', 'Видео'), ('DOCUMENT', 'Документ'), ('AUDIO', 'Аудио'), ('MEDIA_GROUP', 'Медиагруппа (несколько фото)')], help_text="Выберите 'Медиагруппа' для загрузки нескольких фото ниже. В противном случае, загрузите один файл выше.", max_length=15, null=True, verbose_name='Тип медиафайла'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='media_type',
            field=models.CharField(blank=True, choices=[('PHOTO', 'Фото'), ('VIDEO', 'Видео'), ('DOCUMENT', 'Документ'), ('AUDIO', 'Аудио'), ('MEDIA_GROUP', 'Медиагруппа (несколько фото)')], help_text='Необходимо указать тип, если вы прикрепили медиафайл.', max_length=15, null=True, verbose_name='Тип медиафайла'),
        ),
        migrations.CreateModel(
            name='AboutProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Фотография для медиагруппы.', upload_to='about_media_group/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем раньше будет фото в группе.', verbose_name='Порядок сортировки')),
                ('about_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='content.aboutproject', verbose_name="Связь с 'О проекте'")),
            ],
            options={
                'verbose_name': "Медиа для 'О проекте'",
                'verbose_name_plural': "Медиа для 'О проекте'",
                'ordering': ['order'],
            },
        ),
    ]
