# Generated by Django 5.2.5 on 2025-09-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_aboutproject_media_type_alter_faq_media_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Группа единомышленников', 'verbose_name_plural': 'Группа единомышленников'},
        ),
    ]
