# Generated by Django 5.2.5 on 2025-09-16 06:37

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юзернейм')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('height_cm', models.PositiveIntegerField(verbose_name='Рост (см)')),
                ('weight_kg', models.PositiveIntegerField(verbose_name='Вес (кг)')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='ИМТ')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('eaten_products', models.ManyToManyField(blank=True, related_name='eaten_by_users', to='products.product', verbose_name='Съеденные продукты')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
