# Generated by Django 5.2.5 on 2025-09-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenge_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения челленджа'),
        ),
        migrations.AddField(
            model_name='user',
            name='challenge_status',
            field=models.CharField(choices=[('ACTIVE', 'Активен'), ('COMPLETED', 'Завершен (успешно)'), ('EXPIRED', 'Завершен (по времени)')], default='ACTIVE', max_length=10, verbose_name='Статус челленджа'),
        ),
        migrations.AddField(
            model_name='user',
            name='final_eaten_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговое кол-во продуктов'),
        ),
    ]
